# Generated by Django 5.1.5 on 2025-03-05 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfer_payment', '0001_initial'),
        ('transfer_seat', '0001_initial'),
        ('transfer_trip', '0002_remove_trip_arrival_datetime_and_more'),
        ('transfer_vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('payment', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='transfer_payment.payment')),
                ('seats', models.ManyToManyField(blank=True, to='transfer_seat.seat')),
                ('trip', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer_trip.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer_vehicle.vehicle')),
            ],
        ),
    ]
