# Generated by Django 5.1.5 on 2025-03-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
