# Generated by Django 5.1.5 on 2025-03-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_booking', '0001_initial'),
        ('transfer_trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer_trip.trip'),
        ),
    ]
