# Generated by Django 5.1.5 on 2025-03-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_booking', '0002_booking_trip'),
        ('transfer_vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer_vehicle.vehicle'),
        ),
    ]
