# Generated by Django 5.1.5 on 2025-03-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_booking', '0004_booking_is_active'),
        ('transfer_seat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(blank=True, to='transfer_seat.seat'),
        ),
    ]
