# Generated by Django 5.1.5 on 2025-03-05 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_booking', '0005_booking_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 9, 36, 47, 990866, tzinfo=datetime.timezone.utc)),
        ),
    ]
