# Generated by Django 5.1.5 on 2025-03-05 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_booking', '0006_alter_booking_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
