# Generated by Django 5.1.5 on 2025-03-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='arrival_datetime',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='departure_datetime',
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
