# Generated by Django 5.1.5 on 2025-03-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=30)),
                ('total_seats', models.IntegerField()),
            ],
        ),
    ]
