# Generated by Django 5.1.5 on 2025-01-31 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
