# Generated by Django 5.1.5 on 2025-02-10 09:58

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number in international format (e.g., +1234567890)', max_length=128, region=None, unique=True),
        ),
    ]
