# Generated by Django 5.1.5 on 2025-01-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_auth', '0002_remove_user_password_remove_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='null', max_length=12, unique=True),
        ),
    ]
