name: Deploy to Server

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.DEV_SERVER_PORT || '22' }} -H ${{ secrets.DEV_SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
        shell: bash

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy to server
        env:
          DEV_USER: ${{ secrets.DEV_SERVER_USER }}
          DEV_HOST: ${{ secrets.DEV_SERVER_HOST }}
          DEV_PORT: ${{ secrets.DEV_SERVER_PORT || '22' }}
        run: |
          ssh -i ~/.ssh/id_rsa -p $DEV_PORT -o StrictHostKeyChecking=no $DEV_USER@$DEV_HOST << EOF
            cd ~/TransferAPI
            git fetch --all
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            echo "Pulled latest changes from ${{ github.ref_name }}"

            echo "Building Docker containers..."
            docker compose -f docker-compose.prod.yml build

            echo "Starting Docker containers..."
            docker compose -f docker-compose.prod.yml up -d

            echo "Making migrations..."
            docker compose -f docker-compose.prod.yml exec -T web python src/manage.py makemigrations

            echo "Applying migrations..."
            docker compose -f docker-compose.prod.yml exec -T web python src/manage.py migrate

            echo "Cleaning up old Docker images..."
            docker image prune -af

            echo "Deployment to server finished."
          EOF
        shell: bash
